import { ArrowLeft, ArrowRight, BookOpen, Check, FileSearch, ShieldCheck } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { SupportPage } from '../components/support/SupportPage'
import { guideEntries } from '../data/supportContent'

export function GuidePage() {
  const { patternId } = useParams()
  const pattern = guideEntries.find((item) => item.id === patternId)
  if (pattern) return <SupportPage eyebrow="Scam Guide > Pattern" title={pattern.title} description={pattern.description} actions={<Link className="button button-secondary" to="/guide"><ArrowLeft size={16} aria-hidden="true" />All patterns</Link>}><section className="guide-detail-grid"><article className="panel guide-detail"><div className="guide-icon"><BookOpen size={22} aria-hidden="true" /></div><p className="section-label">Why it matters</p><p>{pattern.rationale}</p><p className="section-label">What to do</p><p>{pattern.safetyTip}</p><p className="section-label">Related checklist actions</p><ul className="guide-action-list"><li><Check size={15} aria-hidden="true" />{pattern.safetyTip}</li><li><Check size={15} aria-hidden="true" />Verify through a school coordinator or official company channel before applying.</li></ul><div className="guide-callout"><ShieldCheck size={17} aria-hidden="true" /><span>Hunch describes signals in a post. It does not accuse a company or prove fraud.</span></div><Link className="button button-primary" to={`/analyze?fixture=${pattern.fixtureId}`}><FileSearch size={16} aria-hidden="true" />Try a sample post</Link></article><aside className="panel guide-next"><p className="eyebrow">Keep checking</p><h2>One signal is a reason to verify, not a verdict.</h2><ul className="signal-list"><li><Check size={16} aria-hidden="true" />Confirm the company through an independent channel.</li><li><Check size={16} aria-hidden="true" />Ask for clear role and supervisor details.</li><li><Check size={16} aria-hidden="true" />Do not send money or sensitive documents early.</li></ul></aside></section></SupportPage>
  return <SupportPage eyebrow="Scam Guide" title="Learn the common signals" description="Plain-language patterns from Hunch's rule catalog to help students pause, verify, and decide what to do next."><section className="support-grid guide-grid">{guideEntries.map((item) => <Link className="support-card guide-card" key={item.id} to={`/guide/${item.id}`}><div className="guide-icon"><BookOpen size={18} aria-hidden="true" /></div><strong>{item.title}</strong><span>{item.description}</span><span className="text-link">Read pattern <ArrowRight size={14} aria-hidden="true" /></span></Link>)}</section></SupportPage>
}
